### ISSUE TITLE
module_variable_optional_attrs is deprecated in latest terraform version

### ISSUE THREAD

**Issue by alexvanderberkel** [iits-consulting/terraform-argocd-bootstrap#4]
Hi guys,

this part of the code is no longer supported in the latest version of terraform:

  experiments = [
    module_variable_optional_attrs,
  ]

Cheers,
Alex

**Comment by victorgetz** [comment]
Hi Alex,

i am very sorry we did not see your Report.
We fixxed it today with Version v5.6.0
